I'm incredibly happy to help out the PC handheld gaming community. If my work has made a difference for you, a small gesture like buying me a coffee or a beer would be greatly appreciated. Thank you all for your support!

github: # LostyDEV
USDC: 0xe33d2edde60fd6d16ed55d6452b052e75fdab26a
BNB: 0xe33d2edde60fd6d16ed55d6452b052e75fdab26a
ETH: 0xe33d2edde60fd6d16ed55d6452b052e75fdab26a
SOL: 7vhAB14kEgugxiKogeYhHWxq4SLZ6VHM5o2tdhudFs5p
ADA: addr1qyk0657d7v7d28jdg0jfj6h6506c24tu2v0923fa4gj5alpqecjfja3ge4er9fvux9y2ng3rssa9k7m7dcywa804c63swrwswc
TRX: THUEEj2DKe67p9VwJ27ockjyRgYzvVDbTm
TON: UQCt2l1gbFzRG2TU-48_1u2TxSv4Y-FbxqbmK3rQcTcAeo5_
XRP: rnTZkLsazLn76CfhxNNeGZBWh575Us3EeS
PEPE: 0xe33d2edde60fd6d16ed55d6452b052e75fdab26a
